from __future__ import annotations

import enum
from dataclasses import dataclass
from typing import Optional, Protocol


class IconState(enum.Enum):
    NORMAL = 'normal'
    WEAK = 'weak'
    DISCONNECT = 'disconnect'


@dataclass
class DeviceInfo:
    """Snapshot of the bound device read from IOBluetooth."""
    name: str = ''
    address: str = ''
    connected: bool = False
    rssi: Optional[int] = None


class UIPort(Protocol):
    """Implemented by the ui layer. Implementations marshal onto the main thread."""

    def set_icon(self, state: IconState) -> None: ...

    def set_title(self, text: Optional[str]) -> None: ...

    def set_status_text(self, text: str) -> None: ...

    def set_device_text(self, name: str, address: str, signal: str) -> None: ...

    def set_menu_state(self, key: str, on: bool) -> None: ...

    def notify(self, title: str, subtitle: str, body: str) -> None: ...


class PlatformPort(Protocol):
    """Implemented by the platform layer. The only place that touches macOS."""

    # --- password / keychain ---
    def has_password(self) -> bool: ...

    def set_password(self, password: str) -> None: ...

    def clear_password(self) -> None: ...

    def verify_password(self, password: str) -> bool: ...

    # --- unlock / lock ---
    def unlock(self) -> bool: ...

    def lock(self) -> None: ...

    # --- bluetooth ---
    def bluetooth_info(self, address: str) -> Optional[DeviceInfo]: ...

    def connect(self, address: str) -> bool: ...

    def paired_devices(self) -> list[DeviceInfo]: ...

    def bluetooth_powered_on(self) -> bool: ...

    # --- system state ---
    def check_lid(self) -> Optional[bool]: ...

    def idle_time(self) -> float: ...

    def display_sleep(self) -> bool: ...

    def is_locked(self) -> bool: ...

    def set_require_password_wake(self) -> None: ...

    # --- notifications ---
    def notify(self, title: str, subtitle: str, body: str) -> None: ...

    # --- lifecycle ---
    def accessibility_granted(self) -> bool: ...

    def open_accessibility_settings(self) -> None: ...

    def open_bluetooth_settings(self) -> None: ...

    def has_login_startup(self) -> bool: ...

    def set_login_startup(self, enable: bool) -> bool: ...

    def restart(self) -> None: ...
